ContextPath = ""
HttpPort  = 6879
StartHttp = true
RpcPort = 6979
DevMode = false
ConfigFile = "config-test.toml"

AmberLoginEnabled = false
AmberAppID = ""
AmberEncryptKey = ""
AmberCookieName = "amber-login-auth"
AmberAmberLoginURL = ""
AmberLocalURL = ""
AmberForceLogin = false
