[machines]
    # You can indent as you please. Tabs or spaces. TOML don't care.
    [machines.LOCAL]
    ip = "127.0.0.1"

[logs]
    [logs.DEMO]
    machines = ["LOCAL"]
    path = "aaa.log"
    process = "randomLogGen"

    #[logs.ET]
    #machines = ["LOCAL"]
    #path = "~/gitlab/et-server/target/et-server-0.0.1.log"
    #process = "ET"

[processes]
    [processes.ET]
    home = "~/gitlab/et-server/target"
    ps = "ps aux|grep et-server-0.0.1|grep -v grep"
    kill = "${ps}|awk '{print $2}'|xargs kill -9"
    start = "nohup java -jar et-server-0.0.1.jar 2>&1 >> et-server-0.0.1.log &"

    [processes.randomLogGen]
    home = "~/GitHub/go-devops/"
    ps = "ps aux|grep go-devops|grep randomLogGen|grep -v grep"
    kill = "${ps}|awk '{print $2}'|xargs kill -9"
    start = "nohup ./go-devops -randomLogGen=true 2>&1 >> randomLogGen.out &"


[logrotates]
    [logrotates.yoga-glass-catalina]
    machines = ["LOCAL"]
    files = ["CopyTruncate.log"]
    crons  = ["@every 10s"]
    type = "CopyTruncate"
    parameters = "maxSize=10"

    [logrotates.yoga-glass-dir]
    machines = ["LOCAL"]
    files = ["Delete.log", "DeleteDir"]
    crons  = ["@every 10s"]
    type = "Delete"

    [logrotates.yoga-glass-access]
    machines = ["LOCAL"]
    files = ["./logs"]
    crons  = ["@every 10s"]
    type = "DeleteOlds"
    parameters = "days=3,pattern=log.YYYY-MM-DD.log"

[blackcatThreshold]
    load5Threshold = 0.9
    diskAvailThreshold = "20G"
    diskAvailRatioThreshold = 0.1
    memAvailThreshold = "200M"
    memAvailRatioThreshold = 0.1
    thresholdCron  = "@every 60s"
    exLogsCron  = "@every 10s"
    machines = ["LOCAL"]


[blackcatExLogs]
    [blackcatExLogs.et]
    directRegex = true
    normalRegex = "2017-11-19 23:54:53.026"
    exceptionRegex = "\\.(\\S+)?Exception\\b"
    ignores = [""]
    logFileName = "a.log"
    properties = ["tcode", "tenantCode\\[(\\d+)\\]"]
    machines = ["LOCAL"]

[blackcatProcesses]
   [blackcatProcesses.et]
   keywords=["et-server-0.0.1.jar"]
   machines = ["LOCAL"]


