[machines]
    # You can indent as you please. Tabs or spaces. TOML don't care.
    [machines.LOCAL]
    ip = "127.0.0.1"

[logs]
    [logs.DEMO]
    machines = ["LOCAL"]
    path = "/Users/bingoo/gitlab/hanergy-ceping-server/ceping.log"
    process = "go-devops"

    #[logs.ET]
    #machines = ["LOCAL"]
    #path = "~/gitlab/et-server/target/et-server-0.0.1.log"
    #process = "ET"

[processes]
    [processes.go-devops]
    home = "/Users/bingoo/go/src/github.com/bingoohuang/go-devops"
    ps = "ps aux|grep go-devops|grep -v grep"
    kill = "${ps}|awk '{print $2}'|xargs kill -9"


[blackcatThreshold]
    load5Threshold = 1.5
    diskAvailThreshold = "2G"
    diskAvailRatioThreshold = 0.1
    memAvailThreshold = "100MiB"
    memAvailRatioThreshold = 0.1
    thresholdCron  = "@every 60s"
    exLogsCron  = "@every 10s"
    patrolCron = "0 0 8-20 * * ?"
    machines = ["LOCAL"]
    topn = 30
    messageTargets = ["hanergy-ceping"]
    exLogViewUrlPrefix = "http://127.0.0.1:6879/"

[messageTargets]
    [messageTargets.hanergy-ceping]
    messagingType = "dingtalk-robot"
    properties = "7dbfda32839df27923aa2f6b1a4684bb777b114a45963687ba7cf8506d13dd3e"


[blackcatExLogs]
    [blackcatExLogs.et]
    directRegex = false
    normalRegex = "2017-11-19 23:54:53.026"
    exceptionRegex = "\\.(\\S+)?Exception\\b"
    ignores = [""]
    logFileName = "/Users/bingoo/gitlab/hanergy-ceping-server/ceping.log"
    properties = []
    machines = ["LOCAL"]
    messageTargets = ["hanergy-ceping"]


[blackcatProcesses]
    [blackcatProcesses.et]
    keywords=["go-devops"]
    machines = ["LOCAL"]
    messageTargets = ["hanergy-ceping"]

[httpCheckers]
    [httpCheckers.backupCenter]
    title = "检查备份请求"
    cron = "0 10 08 1/1 * ?"
    url = "http://1.2.3.4:5000/backup/south/YYYYMMDD/err.log"
    ok = "OK"
    okMsg = "南方中心备份成功!"
    failMsg = "备份中心备份异常,详情请查看备份目录err.log!"
    messageTargets = ["hanergy-ceping"]
