[machines]
    # You can indent as you please. Tabs or spaces. TOML don't care.
    [machines.LOCAL]
    ip = "127.0.0.1"

    [machines.LOCAL2]
    ip = "192.168.1.1"

[logs]
    [logs.DEMO]
    machines = ["LOCAL"]
    path = "/Users/bingoo/GitHub/logtest/aa.log"
    process = "ps aux|grep logtest|grep -v grep"
