[machines]
    # You can indent as you please. Tabs or spaces. TOML don't care.
    [machines.LOCAL]
    ip = "127.0.0.1"

[logs]
    [logs.DEMO]
    machines = ["LOCAL"]
    path = "aaa.log"
    process = "ps aux|grep logtest|grep -v grep"
