[machines]
    # You can indent as you please. Tabs or spaces. TOML don't care.
    [machines.LOCAL]
    ip = "127.0.0.1"

[logs]
    [logs.DEMO]
    machines = ["LOCAL"]
    path = "aaa.log"
    process = "randomLogGen"

[processes]

    [processes.randomLogGen]
    home = "~/GitHub/go-devops/"
    ps = "ps aux|grep go-devops|grep randomLogGen|grep -v grep"
    kill = "${ps}|awk '{print $2}'|xargs kill -9"
    start = "nohup ./go-devops -randomLogGen=true 2>&1 >> randomLogGen.out &"
    conf = "config.toml"

